name = "OceanGreensFunctionMethods"
uuid = "e3e8a769-591b-4840-946e-301c93ad313e"
authors = ["G Jake Gebbie <ggebbie@whoi.edu>"]
version = "1.0.2-DEV"

[deps]
DimensionalData = "0703355e-b756-11e9-17c0-8b28908087d0"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
Downloads = "f43a241f-c20a-4ad4-852c-f6b1247861c6"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MAT = "23992714-dd62-5051-b70f-ba57cb901cac"
MultipliableDimArrays = "3e2a59ee-8dc2-49ed-b08b-35477f91d0a4"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"

[compat]
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
